config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'  
  resources :articles
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence:true, length: {minimum: 10, maximum: 3000}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save{
    self.email = email.downcase
  }
  has_many :articles, dependent: :destroy 
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: {with: VALID_EMAIL_REGEX }
        
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method:current_user, :logged_in?
  def current_user
    @currentuser ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user

  end
  def require_user

    if !logged_in?
      flash[:alert] = "you must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only:[:show,:edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show
   
    end
    def index
        @articles = Article.paginate(page: params[:page], per_page: 4)
    end 

    def edit 
        # @article = Article.find(params[:id])

    end

    def new
        @article = Article.new 
    end
    
    def create
        byebug
        @article = Article.new(article_params)
        @article.user = current_user
        # render plain: @article
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to  @article
        else 
            render 'new'
        end
    end

    def update
        # @article = Article.find(params[:id])
       if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
       else
        render 'edit'
       end
    end

    def destroy
        # @article = Article.find(params[:id])
        @article.destroy 
        redirect_to articles_path

    end 
    
    private

    def set_article
        @article = Article.find(params[:id ])
    end
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "you can only edit or delete your own article"
        redirect_to @article
      end
    end


end                

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  def new
    @category = Category.new
  end
  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save 
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      
      render 'new'
    end
  end
  def edit
    @category = Category.find(params[:id])

  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category Name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end

  end
  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end


  private

  def category_params
    
    params.require(:category).permit(:name)
    
  end
  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert]= "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      redirect_to articles_path if logged_in?
    end
    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      
      flash[:notice] = "Logged in successfully"
      redirect_to user

       else

      flash.now[:alert] = 'Invalid email/password combination'
      # byebug
      #  flash.now[:alert] = "there was something wrong with your login details"
       render 'new'

        # byebug
     end
  end
  
  def destroy 
    session[:user_id] = nil
    flash[:notice] = "logged out"
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user , only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def show 

    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end
  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "welcome to the Alpha Blog #{@user.username}, you have successfully signup"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @user.update(user_params)
      flash[:notice] = "YOur account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end

  end
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert]= "you can only edit or delete your own profile"
      redirect_to @user
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def users_profile(user)
  
    user_path = user.username.itself[0,1].to_s.upcase + user.username.match(/(?<=\s)./).to_s.upcase


  end


  
  
  def gravatar_for(user,options = { size: 80 })
    # byebug
    params = {
      :a => user.username.itself[0,1].to_s.upcase + user.username.match(/(?<=\s)./).to_s.upcase
    }
    size = options[:size]
    user_path = user.username.itself[0,1].to_s.upcase + user.username.match(/(?<=\s)./).to_s.upcase
    default_url = "http://www.lse.ac.uk/International-Inequalities/Assets/Images/BlankImage.jpg?h=60&w=60"
    
    # default_url = "http://via.placeholder.com/150/000000/FFFFFF/?text=".concat(user_path)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    gravatar_url= "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI.escape(default_url)}"
    image_tag(gravatar_url, alt:user_path, html: { style: "height: 60px;, width:60px;"}, class: "bg1 rounded-circle shadow mx-auto d-block")
    
    
  
  end

  def show_errors(object, field_name)
    if object.errors.any?
      if !object.errors.messages[field_name].blank?
        object.errors.messages[field_name].first
        
      end
    end
  end 
  
  
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container cont mb-4">
  <% @articles.each do |article|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3 mb-4">
        <div class="card text-center card-1 text-white bg2 ml-4 mr-4 rounded">
          <div class="card-header font-weight-bold  font-italic">
            <% if article.user %>
            
            by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2 ">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body text-white">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: " font-weight-bold text-info"%></h5>
            <p class="card-text"><%= truncate(article.description, length: 10) %></p>
            <%# <a href="#" class="btn btn-outline-success">View</a>
            <a href="#" class="btn btn-outline-info">Edit</a>
            <a href="#" class="btn btn-outline-danger">Delete</a> %>
            <%= link_to 'View', article_path(article), class: "btn btn-outline-success"%>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info"%>
              <%= link_to 'Delete',  article_path(article), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-outline-danger"%>
            <% end %>
          </div>

          <div class="card-footer mb-4 text-white text-muted">
            <small> created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/articles/_error-messages.html.erb
<% if @article.errors.any?%>

    <h2> the following errors prevented the article from being saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
             <li><%=  msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'shared/errors', obj: @article  %>

      <%= form_with(model: @article,class: "shadow p-3 mb-5 bg rounded", local: true) do |f| %>
      <div class="form-group row mt-4">
          <%= f.label :title, class: "col-2 col-form-label text-light"%>
          <div class="col-10">
          <%= f.text_field :title,required: true, class: "form-control shadow rounded", placeholder: "Title of Article"%>
          </div>
      </div>
      <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-control text-light"%>
        <div class="col-10">
          <%= f.text_area :description, required: true, rows: 10, class: "form-control shadow rounded", placeholder:"Description of Article" %>
        </div>
      </div>
      

      <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-control text-light"%>
        <div class="col-10 ">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, size: 2, prompt: true do |b| %>
            <div class = "check1 pt-2 shadow collection-check-box">
              <%= b.check_box class: "ml-4 "%>
              <%= b.label class: "text-white" %>
            </div>
            <% end %>
        </div>
      </div>


      <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-large "%>
      </div>

      <% end %>
    </div>
    <%= link_to '[ cancel or return to article list ]', articles_path, class: "text-info h4" %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="edit-bg">

<h1 class="text-center text-white mt-4">Edit Article</h1>

<%= render 'form'%>
</div>
  

app/views/articles/index.html.erb
<div class="article-bg">
 <%= render 'layouts/messages'%>
<%# <div class="float-right"> %>
  <h1 class="text-center mb-4 text-white" style="margin-top: 40px;">Listing all Articles</h1>
  
   
  <%= render 'article' %>

  <%# </div> %>
  <div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="new-bg">
 
  <h1 class="text-center  text-white mt-4">Create new Article</h1>

  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="article-bg">
 <%= render 'layouts/messages'%>
<h2 class="text-center mt-4 text-white"><%= @article.title %> </h2>
<div class="container cont">
  
  <div class="row justify-content-md-center">
    <div class="col-8 mt-3 mb-4">
      <div class="card card-1 text-center bg2 rounded">
        <div class="card-header text-info font-weight-bold font-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user), size: 40 %>
          <% if @article.categories.any? %>
            <div class="m-2 ">
            <%= render @article.categories %>
            </div>
          <% end %>
        </div>
        <div class="card-body">
          
          <div class="card-text text-white text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info"%>
            <%= link_to 'Delete',  article_path(@article), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-outline-danger"%>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small> created <%= time_ago_in_words(@article.created_at) %> ago,
          Edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
        </div>
      </div>
    </div>
  </div>
  
</div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-light mr-1" %>

app/views/categories/_form.html.erb
 <%= render 'shared/errors', obj: @category  %>
  

  <%= form_with(model: @category,class: "shadow p-3 mb-5 bg rounded", local: true, validate: true) do |f| %>

  <div class="form-group row mt-5">
      <%= f.label :name, "Category Name", for: "user_input", class: "col-2 col-form-label text-light"%>
      <div class="col-10">
      <%= f.text_field :name, id: "user_input", class: "form-control shadow rounded", placeholder: "Enter name"%>
      <p class='error text-danger font-weight-bold'><%= show_errors(@category, :name) %></p>
      </div>
        
  </div>
  
  
  <div class="form-group row mt-2 justify-content-center">
      <%= f.submit class: "btn btn-outline-light btn-lg "%>
      
  </div>

  <% end %>

app/views/categories/edit.html.erb
<div class="new-bg">
 
  <h1 class="text-center text-white mt-5 mb-4">Edit Category</h1>
  <div class="container">
  
  <div class="row justify-content-center">
    <div class="col-8">
      <%= render 'form' %>
    </div>
    
  </div>
  <%= link_to '[ cancel or return to category ]', category_path(@category), class: " row justify-content-center text-info h4" %>
</div>
</div>

app/views/categories/index.html.erb
<div class="category-bg">


    


    <div class="container cont">
    <h1 class="text-center text-white "style="margin-top: 40px;">Categories</h1>
      <% @categories.each do |category|%>
        <div class="row justify-content-md-center">
          <div class="col-8 mt-5 mb-4">
            <div class=" card text-center card-1 text-white bg2 mr-4 rounded">
              
              <div class="card-body text-white">
                <h5 class="card-title"><%= link_to category.name, category_path(category), class: " font-weight-bold text-info"%></h5> 
                <p class="card-text text-light"><%= pluralize(category.articles.count, "article") %></p>
              </div>

              <div class="card-footer mb-4 text-white text-muted">
                <small> created <%= time_ago_in_words(category.created_at) %> ago,
                Edited <%= time_ago_in_words(category.updated_at)%> ago</small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="flickr_pagination mt-4 mb-4">
        <%= will_paginate @categories, :container => false %>
    </div>
  <%# </div> %>
</div>

app/views/categories/new.html.erb
<div class="new-bg">
 
  <h1 class="text-center text-white mt-4 mb-4">Create New Category</h1>
  <div class="container">
  
  <div class="row justify-content-center">
   
    <div class="col-8">
      <%= render 'form' %>
    </div>
    
  </div>
  <%= link_to '[ cancel or return to categories list ]', categories_path, class: " row justify-content-center text-info h4" %>
</div>
</div>

app/views/categories/show.html.erb
<div class="article-bg">
 
  <%= render 'layouts/messages'%>
  <h1 class="text-center text-white mt-5 mb-4">Category: <%= @category.name %></h1>
  
  
  <% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
      <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-outline-info"%>
    </div>
  <% end %>
  <h3 class= " text-center mt-4"> Article </h3>
  <%= render 'articles/article' %>
  <div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky_footer" class="py-4 footer-bg fixed-bottom text-dark-50">
    <div class=" text-center">
        <small>Copyright &copy; <%= link_to "W3Schools", "https://www.w3schools.com/", class:"text-info" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">

  <% flash.each do |name, msg| %>

    <div class="alert alert-<%= name == "notice" ? "success": "danger" %> alert-dismissible fade show mt-3 flash-msg" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  <% end%>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar border-top-0 navbar-expand-lg navbar-fixed navbar-light bg-light">
    <%# <a class="navbar-brand" id="logo"href="#">ALPHA BLOG</a> %>
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
                
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ">
        
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Link</a> %>
          <%= link_to "Bloggers", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to "Create article", new_article_path, class: "dropdown-item"%>
            <% end %>
            <%= link_to "View articles", articles_path, class: "dropdown-item"%>

          </div>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin?%>
              <%= link_to "Create new category", new_category_path, class: "dropdown-item"%>
            <% end %>
            <%= link_to "View Categories", categories_path, class: "dropdown-item"%>

          </div>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "Admin" if current_user.admin? %> <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      
              <%= link_to "View profile", user_path(current_user), class: "dropdown-item"%>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item"%>
               <%= link_to 'Log out', logout_path, class: "dropdown-item", method: :delete%>
              <div class="dropdown-divider"></div>
              <%= link_to "Delete profile",user_path(current_user),class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
             
             
            </div>
        </li>
      <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', root_path, class: "nav-link"%>
        
          </li>
        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
    
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

  <%= render 'layouts/navigation'%>
  <%# <hr class="divider"> %>
 
  
    <%# <iframe src="http://free.timeanddate.com/clock/i7d3u4ou/n4188/szw160/szh160/hbw0/hfc000/cf100/hgr0/hwc000/fav0/fiv0/mqcfff/mql15/mqw4/mqd94/mhcfff/mhl15/mhw4/mhd94/mmv0/hhcbbb/hmcddd/hsceee" frameborder="0" width="160" height="160"></iframe> %>
   <%# <%= render 'layouts/messages'%> 
    <%= yield %>

  <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the About page </h1>

<%= link_to 'Article list', articles_path%> | 
<%= link_to 'Home_page', root_path%>

app/views/pages/home.html.erb
<div id = "home-container">


  <div class="jumbotron jumbotron-fluid text-center text-white">
     <%= render 'layouts/messages'%>
    <div class="container mb-5 bg-1 mt-4 p-4">

        <h1 class="display-4">ALPHA BLOG</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-info btn-lg"%>
         <%= link_to "Log in!", login_path, class: "btn btn-success btn-lg"%>
        <%# <a class="btn btn-info btn-lg" href="#" role="button">Sign up!</a> %>
        </div>
    </div>

    <div class="one">
      
    </div>
</div>

app/views/users/edit.html.erb
<div class="edit-bg">

  <h1 class="text-center text-white mt-4 mb-4">Edit your  profile</h1>

  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="users-bg">
<h1 class="text-center text-white mt-4 mb-4 ">Alpha Bloggers</h1>


<div class="container">
  <% @users.each do |user|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3 mb-4">
        <div class="card card-2 text-center rounded ml-5 mr-5">
          <div class="card-header font-weight-bold font-italic">
            <h5> <%= link_to user.username, user, class: "text-white" %></h5>
          </div>
          <div class="card-body div_a">
            <h5 class="card-title">
            
            <%= link_to user, :action => 'go' do%>
              <div><%= gravatar_for(user) %></div>
              
            <% end %>
            
            </h5>
            <p class="card-text text-light"><%= pluralize(user.articles.count, "article") %></p>
           
            <%= link_to 'View Profile', user, class: "btn btn-outline-success"%>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-info"%>
              <% end %>
              <%if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure want to delete the user account and all associated articles? "} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-dark">
            <small> Joined <%= time_ago_in_words(user.created_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
  <div class="flickr_pagination mt-4 mb-4">
      <%= will_paginate @users, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<div class="new-bg">
 <%# <%= render 'layouts/messages'%> 
  <h1 class="text-center text-white mt-4 mb-4">Signup for Alpha blog</h1>

  <%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="user-show">
 <%= render 'layouts/messages'%>
<div class="container">
<h1 class="text-center text-white mt-5 mb-4">
<%= @user.username %>'s profile</h1>

<%# <%= gravatar_for @user, size: 100 %> 
<%# <div class = "gravatar" style = "background:transparent url(<%= gravatar_image_url(user.email, :gravatar => { :default => 'https://homepages.cae.wisc.edu/~ece533/images/airplane.png'}) ) 0px 0px no-repeat; width:100px; height:100px;"></div> %>
<%#= gravatar_image_tag('sandhyajanu409@gmail.com', :alt => 'user.username')%>
<%# <div class="profileImage"> %>
  <%= gravatar_for @user %>
<%# </div> %>
<% if logged_in? && @user == current_user%>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info"%>
  </div>
<% end %>

<%# <%= image_tag gravatar_for(@user), class: "rounded-circle shadow mx-auto d-block" %>

<h3 class="text-center text-white mt-4 mb-4">Articles</h3>

<div class="container cont">
  <% @articles.each do |article|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3 mb-4">
        <div class="card text-center text-white card-1 bg2 ml-4 mr-4 rounded">
          <div class="card-header font-weight-bold  font-italic">
            <% if article.user %>
            
            by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>


            <% if article.categories.any? %>
              <div class="mt-2 ">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body text-white">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: " font-weight-bold text-info"%></h5>
            <p class="card-text truncate-title"><%= truncate(article.description, length: 50) %></p>
            <%# <a href="#" class="btn btn-outline-success">View</a>
            <a href="#" class="btn btn-outline-info">Edit</a>
            <a href="#" class="btn btn-outline-danger">Delete</a> %>
            <%= link_to 'View', article_path(article), class: "btn btn-outline-success"%>
            <% if logged_in? && article.user == current_user%>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info"%>
              <%= link_to 'Delete',  article_path(article), method: :delete, data: {confirm: "are you sure?"}, class: "btn btn-outline-danger"%>
            <% end %>
          </div>

          <div class="card-footer mb-1 text-white text-muted">
            <small> created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


 <div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

</div>
</div>